[package]
name = "dpts-error"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0.98"
thiserror = "2.0.12"
clap = { workspace = true }
