[package]
name = "dpts-cli"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
dpts-core = {workspace = true}
chrono = {workspace = true}
clap = {workspace = true, features = ["derive"]}
