[workspace]
members = ["dpts-*"]

[workspace.dependencies]
dpts-core = {path = "dpts-core"}
dpts-migration = {path = "dpts-migration"}
chrono = "0.4"
clap = "4.5"
dotenv = "0.15.0"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/fluo10/dpts"

