[package]
name = "dpts"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
dpts-config.workspace = true
dpts-csv.workspace = true
dpts-entity.workspace = true
dpts-error.workspace = true
dpts-migration.workspace = true
dpts-database.workspace = true

[workspace]
members = [".", "dpts-*"]

[workspace.dependencies]
dpts = { path = "." }
dpts-config = { path = "dpts-config" }
dpts-csv = { path = "dpts-csv" }
dpts-database = { path = "dpts-database" }
dpts-entity = { path = "dpts-entity" }
dpts-error = { path = "dpts-error" }
dpts-migration = {path = "dpts-migration"}
chrono = {version = "0.4", features = ["serde"]}
chrono-tz = {version = "0.10.3", features = ["serde"]}
clap = "4.5"
dotenv = "0.15.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0.12"
tokio = "1.44.2"
toml = "0.8.22"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/fluo10/dpts"

