[workspace]
members = ["dpts-*"]

[workspace.dependencies]
dpts-core = {path = "dpts-core"}
anyhow = "1.0"
chrono = "0.4"
thiserror = "2.0"
clap = "4.5"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/fluo10/dpts"

