[package]
name = "progress-pile-app"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
desktop = ["progress-pile-client/desktop"]

[dependencies]
bevy.version = "0.16.0"
progress-pile-client.workspace = true
