[package]
name = "dpts-core"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
anyhow = {workspace = true}
chrono = {workspace = true}
clap = {workspace = true, features = ["derive"]}
thiserror = {workspace = true}
