[package]
name = "dpts-csv"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
dpts-entity = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
csv = "1.3.1"
thiserror.workspace = true
